name: Trigger Tests ManuallyV2

on:
  workflow_dispatch:
    inputs:
      ENV:
        type: choice
        description: 'Select the environment:'
        options:
          - TI
          - TA
          - PP
        required: true
      LANGUAGE:
        type: choice
        description: 'Set a language:'
        options:
          - EN
          - FR
        required: true
      BROWSER:
        type: choice
        description: 'Set a browser:'
        options:
          - Chrome
          - Firefox
          - Edge
        required: true
      TAGS:
        type: choice
        description: 'Select a TE suite:'
        options:
          - Transparency
          - JMap
          - Facebook
          - Employed
        required: true
      TEST_EXECUTION:
        type: string
        description: 'Enter TE prefix or leave it blank if it does not exist:'
        default: ''
        required: false
      USE_JIRA:
        type: boolean
        description: 'Do you want to update TE?'
        default: false
        required: false

env:
  PYTHON_VERSION: '3.12.1'
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

jobs:
  RobotDemoJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Libraries/requirements.txt
        
      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline

      - name: Prepare test environment
        run: |
          TEST_ENV=$(echo ${{ github.event.inputs.ENV }} | tr '[:upper:]' '[:lower:]')
          TEST_LANG=$(echo ${{ github.event.inputs.LANGUAGE }} | tr '[:upper:]' '[:lower:]')
          echo "TEST_ENV=$TEST_ENV" >> $GITHUB_ENV
          echo "TEST_LANG=$TEST_LANG" >> $GITHUB_ENV

          echo "Test Environment: ${{ github.event.inputs.ENV }}"
          echo "Test Language: ${{ github.event.inputs.LANGUAGE }}"
          echo "Test Browser: ${{ github.event.inputs.BROWSER }}"
          echo "Test Tags: ${{ github.event.inputs.TAGS }}"
          echo "TE Prefix: ${{ github.event.inputs.TEST_EXECUTION }}"
          echo "Update TE: ${{ github.event.inputs.USE_JIRA }}"
          
      - name: Run Robot Framework tests with Allure
        id: robot_tests
        continue-on-error: false
        run: |
          robot \
            --listener allure_robotframework:allure-results \
            --variable ENV:${{ env.TEST_ENV }} \
            --variable LANG:${{ env.TEST_LANG }} \
            --variable BROWSER:${{ github.event.inputs.BROWSER }} \
            --variable NEW_TE:${{ github.event.inputs.TEST_EXECUTION }} \
            --variable USE_JIRA:${{ github.event.inputs.USE_JIRA }} \
            --include ${{ github.event.inputs.TAGS }} \

      - name: Generate Allure report
        uses: andgineer/allure-report@v3.6
        if: always()
        with:
          allure-results: allure-results
          website: allure-history

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-history