# run tests manually in the Actions-tab of the project
name: Trigger Tests Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ENV:
        description: 'Set an ENV:'
        # Default value if no value is explicitly provided
        default: ta
        # Input has to be provided for the workflow to run
        required: true
      BROWSER:
        description: 'Set a BROWSER:'
        # Default value if no value is explicitly provided
        default: Chrome
        # Input has to be provided for the workflow to run
        required: true
      LANGUAGE:
        description: 'Set a LANGUAGE:'
        # Default value if no value is explicitly provided
        default: fr
        # Input has to be provided for the workflow to run
        required: true  

jobs:
  # This workflow contains a single job called "build"
  RobotDemoJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #python and robotframework setup
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
        
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Libraries/requirements.txt
      
      - name: Run tests
        run: |
                 robot  AdminDemo.robot
