# run tests manually in the Actions-tab of the project
name: Trigger Tests Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ENV:
        description: 'Set an ENV:'
        # Default value if no value is explicitly provided
        default: ta
        # Input has to be provided for the workflow to run
        required: true
      BROWSER:
        description: 'Set a BROWSER:'
        # Default value if no value is explicitly provided
        default: Chrome
        # Input has to be provided for the workflow to run
        required: true
      LANGUAGE:
        description: 'Set a LANGUAGE:'
        # Default value if no value is explicitly provided
        default: fr
        # Input has to be provided for the workflow to run
        required: true  

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: mkdir reports
        - name: Run Robot Framework Tests
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable ENV:${{ github.event.inputs.ENV }} --variable BROWSER:${{ github.event.inputs.BROWSER }} --variable LANGUAGE:${{ github.event.inputs.LANGUAGE }} " \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
            path: ${{ github.workspace }}/reports
