# run tests manually in the Actions-tab of the project
name: Trigger Tests Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ENV:
        type: environment
        description: 'Select the environment:'
        # Input has to be provided for the workflow to run
        options:
        - TI
        - TA
        - PP
        # Default value if no value is explicitly provided
        # default: ta
        # required: true
      LANG:
        type: language
        description: 'Set a language:'
        # Input has to be provided for the workflow to run
        options:
        - EN
        - FR
        # Default value if no value is explicitly provided
        # default: fr
        # required: true
      BROWSER:
        type: browser
        description: 'Set a browser:'
        # Input has to be provided for the workflow to run
        options:
        - Chrome
        - Firefox
        - Edge
        # Default value if no value is explicitly provided
        #default: Chrome
        #required: true
      TAGS:
        type: Test execution
        description: 'Select a TE suite'
        # Input has to be provided for the workflow to run
        options:
        - Transparency
        - JMap
        - Facebook
        - Employed
      USE_JIRA:
        # Input has to be provided for the workflow to run
        type: boolean
        description: 'Do you want to update TE?'
        
jobs:
  # This workflow contains a single job called "build"
  RobotDemoJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #python and robotframework setup
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
        
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Libraries/requirements.txt
      
      - name: Run tests
        run: |
         TEST_ENV=$(echo ${{ github.event.inputs.ENV }} | tr '[:upper:]' '[:lower:]')
         TEST_LANG=$(echo ${{ github.event.inputs.LANGUAGE }} | tr '[:upper:]' '[:lower:]')
         echo TEST ENVIRONMENT: ${{github.event.inputs.ENV}}
         echo TEST LANGUAGE: ${{github.event.inputs.LANGUAGE}}
         echo TEST BROWSER: ${{github.event.inputs.BROWSER}}
         robot --variable ENV:$TEST_ENV --variable LANG:$TEST_LANG --variable BROWSER:${{ github.event.inputs.BROWSER }} --include ${{ github.event.inputs.TAGS }} .
      - name: Test results
        uses: actions/upload-artifact@v1
        with:
          name: Report
          path: report.html
      - name: Clean up stuff
        run: |
          history
          pwd
